/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package geradordados;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

 /*
 * @author Henrique da Cruz
 */

public class View extends javax.swing.JFrame {
    
public String nome[] = new String[49];       // Variavel com os nomes
public String nomeM[] = new String[49];      // Variavel com os nomes Masculinos
public String nomeF[] = new String[49];      // Variavel com os nomes Femininos
public String sobrenome1[] = new String[29]; // Variavel com os sobrenomes
public String sobrenome2[] = new String[29]; // Variavel com os sobrenomes

public String prefixo[] = new String[4];     // Varivavel com prefixos
public String local[] = new String[26];      // Variavel com nomes de ruas

    /**
     * Create new jFrame called (View)
     */

    public View() {
        initComponents();
        
//ler os .txt de cada variavel
        FileReader nomes;
        FileReader nomesF;
        FileReader nomesM;
        FileReader sobrenomes1;
        FileReader sobrenomes2;
        
        FileReader prefixos;
        FileReader locais;
        
        try {
 
//ler os .txt para as variaveis receber os nomes
            nomes = new FileReader("dados/nome.txt");   
            jTextArea1.read(nomes, null);
            String aux = jTextArea1.getText();
            nome = aux.split("\n");
            
            nomesF = new FileReader("dados/nomeF.txt");   
            jTextArea1.read(nomesF, null);
            String auxF = jTextArea1.getText();
            nomeF = auxF.split("\n"); 
            
            nomesM = new FileReader("dados/nomeM.txt");   
            jTextArea1.read(nomesM, null);
            String auxM = jTextArea1.getText();
            nomeM = auxM.split("\n");
    
//sobrenome1
            sobrenomes1 = new FileReader("dados/sobrenome1.txt");
            jTextArea1.read(sobrenomes1, null);
            aux = jTextArea1.getText();
            sobrenome1 = aux.split("\n"); 
            
//sobrenome2
            sobrenomes2 = new FileReader("dados./sobrenome2.txt");
            jTextArea1.read(sobrenomes2, null);
            aux = jTextArea1.getText();
            sobrenome2 = aux.split("\n"); 
            
//prefixos
            prefixos = new FileReader("dados/prefixo.txt");
            jTextArea1.read(prefixos, null);
            aux = jTextArea1.getText();
            prefixo = aux.split("\n");   // Variavel publica

//nome das ruas
            locais = new FileReader("dados/local.txt");
            jTextArea1.read(locais, null);
            aux = jTextArea1.getText();
            local = aux.split("\n");
            
            
            this.setTitle("Bem vindo");
        } catch (IOException ex){
            this.setTitle("Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerador dados");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jButton1.setText("GERAR DADOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("NOME DO PAI");

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setText("NOME DA MAE");

        jLabel3.setText("NOME USUARIO");

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel4.setText("ENDERECO");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel5.setText("TELEFONE");

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel6.setText("RG");

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel7.setText("CPF");

        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel8.setText("RENDA");

        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel9.setText("NASCIMENTO");

        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jButton1)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

//Limpar os campos

    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jTextField6.setText("");
    jTextField7.setText("");
    jTextField8.setText("");
    jTextField9.setText("");
     
//Nome do pai

        int random = (int)Math.round(Math.random() * 49);
        String nomePai = nomeM[random];                  
       
        random = (int)Math.round(Math.random() * 29);
        nomePai += " " + sobrenome1[random];           
        
        random = (int)Math.round(Math.random() * 29);
        nomePai += " " + sobrenome2[random];            
        
        jTextField1.setText(nomePai);                
        
//Nome da mãe

        random = (int)Math.round(Math.random() * 49);
        String nomeMae = nomeF[random];                    
        
        random = (int)Math.round(Math.random() * 29);
        nomeMae += " " + sobrenome1[random];              
        
        random = (int)Math.round(Math.random() * 29);
        nomeMae += " " + sobrenome2[random];                 
        
        jTextField2.setText(nomeMae);              
        
//Nome completo do usuario

//selecionando o sobrenome da mãe, pode ser qualquer sobrenome
       random = (int)Math.round(Math.random() * 49);
       String nomeUser = nome[random];
       
       random = (int)Math.round(Math.random() * 2);
       if(random == 0){//se pegar o primeiro nome, incrementa para pegar o sobrenome
           random += 1;
       }
       String aux[] = nomeMae.split(" ");//.split para separar a string como array
       nomeUser += " " + aux[random];
       
//selecionando o sobrenome da pai
       random = (int)Math.round(Math.random() * 2);
       if(random == 0){ //se pegar o primeiro nome, incrementa para pegar o sobrenome
           random += 2;
       }
       aux = nomePai.split(" ");                       
       nomeUser += " " + aux[random];
       
       jTextField3.setText(nomeUser);                  
      
//Nome da Rua
       String nomeLocal;

       random = (int)Math.round(Math.random() * 4);
       nomeLocal = prefixo[random];                    // Add prefixo
       
       random = (int)Math.round(Math.random() * 26);
       nomeLocal += " " + local[random];               // Add nome
       
       random = (int)Math.round(Math.random() * 999);
       nomeLocal += ", " + random;                     // Add numero
       
       jTextField4.setText(nomeLocal);                 // Mostra nome
       

//Numero do Telefone

       String telefone = "";
       
//Gera o ddd
       for(int i = 0; i <= 1; i++){
           random = (int)Math.round(Math.random() * 9);
           telefone += Integer.toString(random);
       }
       
       telefone += " "; // Separa o DDD do numero em si
       
//Gera o telefone
       for(int i = 0; i <= 1; i ++){         
           for(int j = 0; j <= 3; j++){
               random = (int)Math.round(Math.random() * 9);
               telefone += Integer.toString(random);
           }
           if(i == 0) telefone += "-";// Coloca o traço do numero
       }
       
       jTextField5.setText(telefone);
       
//RG

       String rg = "";

// gera os primeiros digitos
       for(int i = 0; i <= 1; i++){
           random = (int)Math.round(Math.random() * 9);
           rg += Integer.toString(random);
       }   
       rg += ".";
       
// Numeros do meio do rg
       for(int i = 0; i <= 1; i ++){         
           for(int j = 0; j <= 2; j++){
               random = (int)Math.round(Math.random() * 9);
               rg += Integer.toString(random);
           }
           if(i == 0) rg += "."; // Coloca o ponto do rg
       }
       random = (int)Math.round(Math.random() * 9);  // Utimo digito
       rg += "-" + Integer.toString(random);
       
       jTextField6.setText(rg);   
 
//CPF

       String cpf = "";
       
// Numeros do cpf
       for(int i = 0; i <= 2; i ++){         
           for(int j = 0; j <= 2; j++){
               random = (int)Math.round(Math.random() * 9);
               cpf += Integer.toString(random);
           }
           if(i == 0 || i == 1) cpf += "."; // Coloca o ponto do cpf
       }
       
       cpf += "/";      // Barra que separa os 2 ultimos digitos
       
       for(int i = 0; i <= 1; i++){
           random = (int)Math.round(Math.random() * 9);  // Ultimos 2 digitos
           cpf += Integer.toString(random);
       }
       
       jTextField7.setText(cpf);        
       
//Renda
        String renda = "R$ ";
        
        random = (int)Math.round(Math.random() * 15000);
        while(true){
            if(random >= 1500 && random % 100 == 0){ // Verifica se esta correto
                renda += Integer.toString(random);
                break;
            }
            random = (int)Math.round(Math.random() * 15000);
        } 
        renda += ",00"; // adiciona centavos
        
        jTextField8.setText(renda);
        
//Data de Nascimento

    String nascimento = "";

// Gera o dia
    random = (int)Math.round(Math.random() * 30);
    while(true){
        if(random >= 01){ // Para nao deixar data 0
            if(random <= 9){// caso a data for menor ou igual a  9, acresceta o "0"
                nascimento += "0" + Integer.toString(random) + "/";
                break;
            }
            else{
                nascimento += Integer.toString(random) + "/";
                break;
            }
        }
    }
// Gera o mes
    random = (int)Math.round(Math.random() * 12);
    while(true){
        if(random >= 01){ // Para nao deixar data 0
            if(random <= 9){ // caso a data for menor ou igual a  9, acresceta o "0"
                nascimento += "0" + Integer.toString(random) + "/";
                break;
            }
            else{
                nascimento += Integer.toString(random) + "/";
                break;
            }
        }
    }
    
// Gera o ano
    random = (int)Math.round(Math.random() * 2004);
        while(true){ 
            if(random >= 1922){//Verifica se esta correto
                nascimento += Integer.toString(random);
                break;
            }
            random = (int)Math.round(Math.random() * 2004);
        }
    

    jTextField9.setText(nascimento);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
